# Generated by Django 3.2.18 on 2023-03-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='material',
        ),
        migrations.AddField(
            model_name='apply',
            name='material',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
